export const aggregateExportDataSources = {
  'eo_impression': 'Impressions',
  'eo_click': 'Clicks',
  'eo_branch_cta_view': 'CTA Views',
  'eo_sms_sent': 'SMS Sent',
  'eo_open': 'Opens',
  'eo_install': 'Installs',
  'eo_reinstall': 'Reinstalls',
  'eo_web_session_start': 'Web Session Starts',
  'eo_pageview': 'Pageviews',
  'eo_commerce_event': 'Commerce Events',
  'eo_custom_event': 'Custom Events',
  'eo_content_event': 'Content Events',
  'eo_dismissal': 'Dismissals',
  'eo_user_lifecycle_event': 'User Lifecycle Events',
  'cost': 'Cost Data',
  'skadnetwork-valid-messages': 'SKAdNetwork Valid Messages',
  'eo_click_blocked': 'Blocked Clicks',
  'eo_impression_blocked': 'Blocked Impressions',
  'eo_install_blocked': 'Blocked Installs',
  'eo_reinstall_blocked': 'Blocked Reinstalls',
  'eo_open_blocked': 'Blocked Opens',
  'eo_web_session_start_blocked': 'Blocked Web Session Starts',
  'eo_pageview_blocked': 'Blocked Pageviews',
  'eo_sms_sent_blocked': 'Blocked SMS Sent',
  'eo_custom_event_blocked': 'Blocked Custom Events',
  'eo_content_event_blocked': 'Blocked Content Events',
  'eo_commerce_event_blocked': 'Blocked Commerce Events',
  'eo_user_lifecycle_event_blocked': 'Blocked User Lifecycle Events',
  'eo_branch_cta_view_blocked': 'Blocked CTA Views'
};

export const aggregateExportDimensions = {
  name: 'The name of the event or a timestamp for the data point.',
  origin: 'The origin of the event.',
  timestamp: 'The timestamp of the event in ISO-8601 format.',
  deep_linked: 'Indicates if the user was deep linked.',
  from_desktop: 'Indicates if the event originated from a desktop device.',
  attributed: 'Indicates if the event was attributed to a marketing touch.',
  user_data_app_store: 'The app store from which the app was installed.',
  user_data_app_version: 'The version of the app.',
  user_data_os: 'The operating system of the user\'s device.',
  user_data_language: 'The language setting of the user\'s device.',
  user_data_platform: 'The platform of the user\'s device (e.g., IOS, ANDROID).',
  user_data_environment: 'The environment of the app (e.g., FULL_APP, WEB_VIEW).',
  user_data_geo_region_en: 'The geographical region of the user (in English).',
  user_data_geo_dma_code: 'The Designated Market Area code for the user\'s location.',
  user_data_geo_country_code: 'The country code of the user\'s location.',
  user_data_country: 'The country of the user\'s location.',
  user_data_cpp_level: 'The level of data privacy consent provided by the user.',
  user_data_opted_in: 'Indicates if the user has opted into tracking.',
  user_data_opted_in_status: 'The status of the user\'s opt-in.',
  last_attributed_touch_type: 'The type of the last touch that led to attribution (e.g., click, impression).',
  last_attributed_touch_data_tilde_tags: 'Tags associated with the last attributed touch.',
  last_attributed_touch_data_tilde_secondary_publisher: 'The secondary publisher of the last attributed touch.',
  last_attributed_touch_data_plus_current_feature: 'The feature associated with the current touch.',
  last_attributed_touch_data_plus_via_features: 'Features involved in the user journey.',
  last_attributed_touch_data_plus_aggregate_measurement: 'Aggregate measurement data.',
  last_attributed_touch_data_plus_pam_enabled: 'Indicates if Private Ad Measurement was enabled.',
  last_attributed_touch_data_tilde_campaign: 'The campaign name of the last attributed touch.',
  last_attributed_touch_data_tilde_advertising_partner_name: 'The name of the advertising partner.',
  last_attributed_touch_data_tilde_advertising_partner_id: 'The ID of the advertising partner.',
  last_attributed_touch_data_tilde_feature: 'The feature of the last attributed touch.',
  last_attributed_touch_data_tilde_creative_name: 'The name of the creative.',
  last_attributed_touch_data_plus_web_format: 'The web format of the touch.',
  last_attributed_touch_data_tilde_creative_id: 'The ID of the creative.',
  last_attributed_touch_data_tilde_ad_name: 'The name of the ad.',
  last_attributed_touch_data_tilde_ad_id: 'The ID of the ad.',
  last_attributed_touch_data_tilde_campaign_id: 'The ID of the campaign.',
  last_attributed_touch_data_tilde_placement: 'The placement of the ad.',
  last_attributed_touch_data_tilde_stage: 'The stage in the user journey.',
  last_attributed_touch_data_tilde_channel: 'The marketing channel.',
  last_attributed_touch_data_tilde_ad_set_name: 'The name of the ad set.',
  last_attributed_touch_data_tilde_ad_set_id: 'The ID of the ad set.',
  last_attributed_touch_data_tilde_keyword: 'The keyword associated with the touch.',
  last_attributed_touch_data_tilde_journey_id: 'The ID of the Journey.',
  last_attributed_touch_data_tilde_view_name: 'The name of the view in the Journey.',
  last_attributed_touch_data_tilde_view_id: 'The ID of the view in the Journey.',
  last_attributed_touch_data_tilde_agency: 'The agency associated with the touch.',
  last_attributed_touch_data_tilde_agency_id: 'The ID of the agency.',
  last_cta_view_data_tilde_ad_name: 'The ad name from the last CTA view.',
  last_cta_view_data_tilde_secondary_publisher: 'The secondary publisher from the last CTA view.',
  last_cta_view_data_tilde_campaign: 'The campaign from the last CTA view.',
  last_cta_view_data_tilde_advertising_partner_name: 'The advertising partner from the last CTA view.',
  last_cta_view_data_tilde_feature: 'The feature from the last CTA view.',
  last_cta_view_data_tilde_ad_set_name: 'The ad set name from the last CTA view.',
  last_cta_view_data_tilde_ad_set_id: 'The ad set ID from the last CTA view.',
  last_cta_view_data_tilde_campaign_id: 'The campaign ID from the last CTA view.',
  last_cta_view_data_tilde_creative_name: 'The creative name from the last CTA view.',
  last_cta_view_data_tilde_creative_id: 'The creative ID from the last CTA view.',
  last_cta_view_data_plus_via_features: 'The features from the last CTA view.',
  last_cta_view_data_dollar_3p: 'Third-party data from the last CTA view.',
  last_cta_view_data_tilde_tags: 'Tags from the last CTA view.',
  last_cta_view_data_plus_web_format: 'The web format from the last CTA view.',
  last_cta_view_data_tilde_channel: 'The channel from the last CTA view.',
  last_cta_view_data_tilde_ad_id: 'The ad ID from the last CTA view.',
  last_cta_view_data_tilde_stage: 'The stage from the last CTA view.',
  body_ad_network_id: 'The ad network ID.',
  body_campaign_id: 'The campaign ID from the request body.',
  body_app_id: 'The app ID from the request body.',
  body_redownload: 'Indicates if the app was redownloaded.',
  body_source_app_id: 'The source app ID.',
  body_source_identifier: 'The source identifier.',
  body_conversion_value: 'The conversion value from SKAdNetwork.',
  body_coarse_conversion_value: 'The coarse conversion value from SKAdNetwork.',
  body_last_attributed_touch_data_tilde_creative_name: 'Creative name from the last attributed touch in the body.',
  body_last_attributed_touch_data_tilde_ad_set_name: 'Ad set name from the last attributed touch in the body.',
  body_last_attributed_touch_data_tilde_creative_id: 'Creative ID from the last attributed touch in the body.',
  body_last_attributed_touch_data_tilde_ad_set_id: 'Ad set ID from the last attributed touch in the body.',
  body_last_attributed_touch_data_tilde_ad_name: 'Ad name from the last attributed touch in the body.',
  body_last_attributed_touch_data_tilde_ad_id: 'Ad ID from the last attributed touch in the body.',
  body_last_attributed_touch_data_tilde_campaign_id: 'Campaign ID from the last attributed touch in the body.',
  body_last_attributed_touch_data_tilde_campaign_name: 'Campaign name from the last attributed touch in the body.',
  annotation_dollar_3p: 'Third-party annotations.',
  annotation_conversion_value_mapped_value: 'The mapped value of the conversion value.',
  annotation_conversion_value_revision: 'The revision of the conversion value mapping.',
  annotation_campaign_id_mapped_value: 'The mapped value of the campaign ID.',
  annotation_campaign_id_revision: 'The revision of the campaign ID mapping.',
  annotation_source_app_id_mapped_value: 'The mapped value of the source app ID.',
  annotation_source_app_id_revision: 'The revision of the source app ID mapping.',
  body_last_attributed_touch_data_tilde_campaign: 'Campaign from the last attributed touch in the body.',
  annotation_customer_event_alias: 'The alias for the customer event.',
  days_from_last_attributed_touch_to_event: 'The number of days between the last attributed touch and the event.',
  days_from_last_cta_view_to_event: 'The number of days between the last CTA view and the event.',
  event_data_product_categories: 'The product categories associated with the event.',
  event_data_custom_param_1: 'Custom parameter 1 for the event.',
  event_data_custom_param_2: 'Custom parameter 2 for the event.',
  event_data_custom_param_3: 'Custom parameter 3 for the event.',
  first_event_for_user: 'Indicates if this is the first event for the user.',
  customer_event_alias: 'The alias for the customer event.'
};