
export const installCohortDimensions = {
  'install_activity_attributed': 'Indicates if the install was attributed.',
  'install_activity_event_name': 'The name of the event associated with the install.',
  'install_activity_touch_type': 'The type of touchpoint for the install.',
  'install_activity_touch_data_tilde_campaign_id': 'The campaign ID for the install touchpoint.',
  'install_activity_touch_data_tilde_campaign': 'The campaign name for the install touchpoint.',
  'install_activity_touch_data_tilde_channel': 'The channel for the install touchpoint.',
  'install_activity_touch_data_tilde_feature': 'The feature for the install touchpoint.',
  'install_activity_touch_data_tilde_stage': 'The stage for the install touchpoint.',
  'install_activity_touch_data_tilde_tags': 'Tags associated with the install touchpoint.',
  'install_activity_touch_data_tilde_advertising_partner_name': 'The advertising partner for the install.',
  'install_activity_touch_data_dollar_3p': 'Third-party data associated with the install.',
  'install_activity_touch_data_tilde_secondary_publisher': 'The secondary publisher for the install.',
  'install_activity_touch_data_tilde_creative_name': 'The creative name for the install touchpoint.',
  'install_activity_touch_data_tilde_ad_id': 'The ad ID for the install touchpoint.',
  'install_activity_touch_data_tilde_ad_set_id': 'The ad set ID for the install touchpoint.',
  'install_activity_touch_data_tilde_ad_set_name': 'The ad set name for the install touchpoint.',
  'install_activity_touch_data_tilde_ad_name': 'The ad name for the install touchpoint.',
  'install_activity_touch_data_tilde_keyword': 'The keyword for the install touchpoint.',
  'install_activity_touch_data_tilde_journey_name': 'The journey name for the install touchpoint.',
  'install_activity_touch_data_tilde_view_name': 'The view name for the install touchpoint.',
  'install_activity_touch_data_plus_referring_domain': 'The referring domain for the install.',
  'install_activity_touch_data_plus_via_features': 'Features involved in the install journey.',
  'install_activity_touch_data_plus_web_format': 'The web format of the install touchpoint.',
  'install_activity_data_os': 'The operating system of the device at install.',
  'install_activity_data_environment': 'The environment of the app at install.',
  'install_activity_data_platform': 'The platform of the device at install.',
  'install_activity_data_country_code': 'The country code of the user at install.',
  'install_activity_data_has_app': 'Indicates if the user had the app at install.',
  'install_activity_data_has_clicked_email': 'Indicates if the user clicked an email before install.',
  'install_activity_data_has_clicked_ad': 'Indicates if the user clicked an ad before install.',
  'install_activity_timezone_adjusted_day': 'The day of install, adjusted for timezone.',
  'install_activity_touch_data_tilde_placement': 'The ad placement for the install touchpoint.',
  'install_activity_data_device_type': 'The device type of the user at install.',
  'install_activity_touch_data_tilde_sub_site_name': 'The sub-site name for the install touchpoint.',
  'install_activity_data_brand': 'The device brand of the user at install.',
  'install_activity_data_geo_country_en': 'The country of the user at install (in English).',
  'install_activity_data_model': 'The device model of the user at install.',
  'install_activity_data_geo_region_en': 'The geographical region of the user at install (in English).',
  'install_activity_touch_data_tilde_customer_secondary_publisher': 'The customer-defined secondary publisher.',
  'install_activity_touch_data_tilde_customer_placement': 'The customer-defined placement.',
  'install_activity_touch_data_tilde_customer_sub_site_name': 'The customer-defined sub-site name.',
  'install_activity_touch_data_tilde_customer_campaign': 'The customer-defined campaign.',
  'install_activity_touch_data_tilde_customer_ad_set_name': 'The customer-defined ad set name.',
  'install_activity_touch_data_tilde_customer_ad_name': 'The customer-defined ad name.',
  'install_activity_touch_data_tilde_customer_keyword': 'The customer-defined keyword.',
  'install_activity_touch_data_tilde_agency_id': 'The agency ID for the install touchpoint.',
  'install_activity_touch_data_tilde_agency': 'The agency name for the install touchpoint.',
  'customer_event_alias': 'The alias for the customer event.'
};

export const reengagementCohortDimensions = {
  'reengagement_activity_attributed': 'Indicates if the re-engagement was attributed.',
  'reengagement_activity_event_name': 'The name of the event associated with the re-engagement.',
  'reengagement_activity_touch_type': 'The type of touchpoint for the re-engagement.',
  'reengagement_activity_touch_data_tilde_campaign_id': 'The campaign ID for the re-engagement touchpoint.',
  'reengagement_activity_touch_data_tilde_campaign': 'The campaign name for the re-engagement touchpoint.',
  'reengagement_activity_touch_data_tilde_channel': 'The channel for the re-engagement touchpoint.',
  'reengagement_activity_touch_data_tilde_feature': 'The feature for the re-engagement touchpoint.',
  'reengagement_activity_touch_data_tilde_stage': 'The stage for the re-engagement touchpoint.',
  'reengagement_activity_touch_data_tilde_tags': 'Tags associated with the re-engagement touchpoint.',
  'reengagement_activity_touch_data_tilde_advertising_partner_name': 'The advertising partner for the re-engagement.',
  'reengagement_activity_touch_data_dollar_3p': 'Third-party data associated with the re-engagement.',
  'reengagement_activity_touch_data_tilde_secondary_publisher': 'The secondary publisher for the re-engagement.',
  'reengagement_activity_touch_data_tilde_creative_name': 'The creative name for the re-engagement touchpoint.',
  'reengagement_activity_touch_data_tilde_ad_id': 'The ad ID for the re-engagement touchpoint.',
  'reengagement_activity_touch_data_tilde_ad_set_id': 'The ad set ID for the re-engagement touchpoint.',
  'reengagement_activity_touch_data_tilde_ad_set_name': 'The ad set name for the re-engagement touchpoint.',
  'reengagement_activity_touch_data_tilde_ad_name': 'The ad name for the re-engagement touchpoint.',
  'reengagement_activity_touch_data_tilde_keyword': 'The keyword for the re-engagement touchpoint.',
  'reengagement_activity_touch_data_tilde_journey_name': 'The journey name for the re-engagement touchpoint.',
  'reengagement_activity_touch_data_tilde_view_name': 'The view name for the re-engagement touchpoint.',
  'reengagement_activity_touch_data_plus_referring_domain': 'The referring domain for the re-engagement.',
  'reengagement_activity_touch_data_plus_via_features': 'Features involved in the re-engagement journey.',
  'reengagement_activity_touch_data_plus_web_format': 'The web format of the re-engagement touchpoint.',
  'reengagement_activity_data_os': 'The operating system of the device at re-engagement.',
  'reengagement_activity_data_environment': 'The environment of the app at re-engagement.',
  'reengagement_activity_data_platform': 'The platform of the device at re-engagement.',
  'reengagement_activity_data_country_code': 'The country code of the user at re-engagement.',
  'reengagement_activity_data_has_app': 'Indicates if the user had the app at re-engagement.',
  'reengagement_activity_data_has_clicked_email': 'Indicates if the user clicked an email before re-engagement.',
  'reengagement_activity_data_has_clicked_ad': 'Indicates if the user clicked an ad before re-engagement.',
  'reengagement_activity_timezone_adjusted_day': 'The day of re-engagement, adjusted for timezone.',
  'reengagement_activity_touch_data_tilde_placement': 'The ad placement for the re-engagement touchpoint.',
  'reengagement_activity_data_device_type': 'The device type of the user at re-engagement.',
  'reengagement_activity_touch_data_tilde_sub_site_name': 'The sub-site name for the re-engagement touchpoint.',
  'reengagement_activity_data_brand': 'The device brand of the user at re-engagement.',
  'reengagement_activity_data_geo_country_en': 'The country of the user at re-engagement (in English).',
  'reengagement_activity_data_model': 'The device model of the user at re-engagement.',
  'reengagement_activity_data_geo_region_en': 'The geographical region of the user at re-engagement (in English).',
  'reengagement_activity_touch_data_tilde_customer_secondary_publisher': 'The customer-defined secondary publisher for re-engagement.',
  'reengagement_activity_touch_data_tilde_customer_placement': 'The customer-defined placement for re-engagement.',
  'reengagement_activity_touch_data_tilde_customer_sub_site_name': 'The customer-defined sub-site name for re-engagement.',
  'reengagement_activity_touch_data_tilde_customer_campaign': 'The customer-defined campaign for re-engagement.',
  'reengagement_activity_touch_data_tilde_customer_ad_set_name': 'The customer-defined ad set name for re-engagement.',
  'reengagement_activity_touch_data_tilde_customer_ad_name': 'The customer-defined ad name for re-engagement.',
  'reengagement_activity_touch_data_tilde_customer_keyword': 'The customer-defined keyword for re-engagement.',
  'reengagement_activity_touch_data_tilde_agency_id': 'The agency ID for the re-engagement touchpoint.',
  'reengagement_activity_touch_data_tilde_agency': 'The agency name for the re-engagement touchpoint.'
};

export const userDimensions = {
  'user_data_platform': 'The platform of the user\'s device.',
  'user_data_environment': 'The environment of the app.',
  'user_data_geo_country_code': 'The country code of the user.',
  'user_data_os': 'The operating system of the user\'s device.',
  'user_data_has_app': 'Indicates if the user has the app installed.',
  'user_data_standard_events_completed': 'Standard events completed by the user.',
  'user_data_custom_events_completed': 'Custom events completed by the user.',
  'user_data_has_clicked_ad': 'Indicates if the user has clicked an ad.',
  'user_data_has_clicked_email': 'Indicates if the user has clicked an email.',
  'user_data_brand': 'The brand of the user\'s device.',
  'user_data_device_type': 'The type of the user\'s device.',
  'user_data_model': 'The model of the user\'s device.'
};

export const otherDimensions = {
  'app_id': 'The ID of the application.',
  'customer_event_alias': 'The alias for a custom event.'
};

export const cohortMeasures = {
  'OPEN': 'Number of app opens.',
  'users': 'Number of unique users.',
  'Retention': 'User retention rate.',
  'ARPPU': 'Average Revenue Per Paying User.',
  'LTV': 'Lifetime Value of users.',
  'ARPU': 'Average Revenue Per User.',
  'revenue': 'Total revenue generated.',
  'PURCHASE': 'Number of purchase events.',
  'ADD_TO_CART': 'Number of add to cart events.',
  'ADD_TO_WISHLIST': 'Number of add to wishlist events.',
  'VIEW_CART': 'Number of view cart events.',
  'INITIATE_PURCHASE': 'Number of initiate purchase events.',
  'ADD_PAYMENT_INFO': 'Number of add payment info events.',
  'SPEND_CREDITS': 'Number of spend credits events.',
  'RESERVE': 'Number of reserve events.',
  'CLICK_AD': 'Number of ad clicks.',
  'VIEW_AD': 'Number of ad views.',
  'SEARCH': 'Number of search events.',
  'VIEW_ITEM': 'Number of view item events.',
  'VIEW_ITEMS': 'Number of view items events.',
  'RATE': 'Number of rate events.',
  'SHARE': 'Number of share events.',
  'COMPLETE_REGISTRATION': 'Number of complete registration events.',
  'COMPLETE_TUTORIAL': 'Number of complete tutorial events.',
  'ACHIEVE_LEVEL': 'Number of achieve level events.',
  'UNLOCK_ACHIEVEMENT': 'Number of unlock achievement events.',
  'INVITE': 'Number of invite events.',
  'LOGIN': 'Number of login events.',
  'SUBSCRIBE': 'Number of subscribe events.',
  'START_TRIAL': 'Number of start trial events.',
  'cost': 'Total cost.',
  'GROSS_PROFIT': 'Gross profit.',
  'ROI': 'Return on Investment.',
  'ROAS': 'Return on Ad Spend.',
  'eCPA': 'Effective Cost Per Acquisition.'
};