
export const crossEventExportDimensions = {
  'last_op': 'Last Operation',
  'link_alias': 'Link Alias',
  'link_archived': 'Link Archived',
  'link_creation_source': 'Link Creation Source',
  'link_dollar_sign_3p': 'Link 3rd Party',
  'link_dollar_sign_android_deeplink_path': 'Link Android Deeplink Path',
  'link_dollar_sign_android_deepview': 'Link Android Deepview',
  'link_dollar_sign_android_passive_deepview': 'Link Android Passive Deepview',
  'link_dollar_sign_android_url': 'Link Android URL',
  'link_dollar_sign_canonical_identifier': 'Link Canonical Identifier',
  'link_dollar_sign_canonical_url': 'Link Canonical URL',
  'link_dollar_sign_deeplink_path': 'Link Deeplink Path',
  'link_dollar_sign_desktop_deeplink_path': 'Link Desktop Deeplink Path',
  'link_dollar_sign_desktop_deepview': 'Link Desktop Deepview',
  'link_dollar_sign_desktop_passive_deepview': 'Link Desktop Passive Deepview',
  'link_dollar_sign_desktop_url': 'Link Desktop URL',
  'link_dollar_sign_fallback_url': 'Link Fallback URL',
  'link_dollar_sign_ios_deeplink_path': 'Link iOS Deeplink Path',
  'link_dollar_sign_ios_deepview': 'Link iOS Deepview',
  'link_dollar_sign_ios_passive_deepview': 'Link iOS Passive Deepview',
  'link_dollar_sign_ios_url': 'Link iOS URL',
  'link_dollar_sign_marketing_title': 'Link Marketing Title',
  'link_dollar_sign_og_description': 'Link OG Description',
  'link_dollar_sign_og_image_url': 'Link OG Image URL',
  'link_dollar_sign_og_title': 'Link OG Title',
  'link_dollar_sign_og_type': 'Link OG Type',
  'link_dollar_sign_og_url': 'Link OG URL',
  'link_dollar_sign_uri_redirect_mode': 'Link URI Redirect Mode',
  'link_dollar_sign_web_only': 'Link Web Only',
  'link_domain': 'Link Domain',
  'link_id': 'Link ID',
  'link_tilde_campaign': 'Link Campaign',
  'link_tilde_channel': 'Link Channel',
  'link_tilde_feature': 'Link Feature',
  'link_tilde_quick_link_template_id': 'Link Quick Link Template ID',
  'link_tilde_tags': 'Link Tags',
  'link_type': 'Link Type',
  'app_id': 'App ID',
  'app_name': 'App Name',
  'attributed': 'Attributed',
  'body_ad_network_id': 'Body Ad Network ID',
  'body_app_id': 'Body App ID',
  'body_campaign_id': 'Body Campaign ID',
  'body_conversion_value': 'Body Conversion Value',
  'body_last_attributed_touch_data_tilde_ad_id': 'Body Last Attributed Touch Ad ID',
  'body_last_attributed_touch_data_tilde_ad_name': 'Body Last Attributed Touch Ad Name',
  'body_last_attributed_touch_data_tilde_ad_set_id': 'Body Last Attributed Touch Ad Set ID',
  'body_last_attributed_touch_data_tilde_ad_set_name': 'Body Last Attributed Touch Ad Set Name',
  'body_last_attributed_touch_data_tilde_campaign': 'Body Last Attributed Touch Campaign',
  'body_last_attributed_touch_data_tilde_campaign_id': 'Body Last Attributed Touch Campaign ID',
  'body_last_attributed_touch_data_tilde_campaign_name': 'Body Last Attributed Touch Campaign Name',
  'body_last_attributed_touch_data_tilde_creative_id': 'Body Last Attributed Touch Creative ID',
  'body_last_attributed_touch_data_tilde_creative_name': 'Body Last Attributed Touch Creative Name',
  'body_redownload': 'Body Redownload',
  'body_source_app_id': 'Body Source App ID',
  'deep_linked': 'Deep Linked',
  'name': 'Name',
  'organization_id': 'Organization ID',
  'origin': 'Origin',
  'last_attributed_touch_data_dollar_3p': 'Last Attributed Touch 3rd Party',
  'last_attributed_touch_data_dollar_marketing_title': 'Last Attributed Touch Marketing Title',
  'last_attributed_touch_data_plus_current_feature': 'Last Attributed Touch Current Feature',
  'last_attributed_touch_data_plus_referring_domain': 'Last Attributed Touch Referring Domain',
  'last_attributed_touch_data_plus_via_features': 'Last Attributed Touch Via Features',
  'last_attributed_touch_data_plus_web_format': 'Last Attributed Touch Web Format',
  'last_attributed_touch_data_tilde_ad_id': 'Last Attributed Touch Ad ID',
  'last_attributed_touch_data_tilde_ad_name': 'Last Attributed Touch Ad Name',
  'last_attributed_touch_data_tilde_ad_set_id': 'Last Attributed Touch Ad Set ID',
  'last_attributed_touch_data_tilde_ad_set_name': 'Last Attributed Touch Ad Set Name',
  'last_attributed_touch_data_tilde_advertising_partner_id': 'Last Attributed Touch Advertising Partner ID',
  'last_attributed_touch_data_tilde_advertising_partner_name': 'Last Attributed Touch Advertising Partner Name',
  'last_attributed_touch_data_tilde_agency': 'Last Attributed Touch Agency',
  'last_attributed_touch_data_tilde_agency_id': 'Last Attributed Touch Agency ID',
  'last_attributed_touch_data_tilde_campaign': 'Last Attributed Touch Campaign',
  'last_attributed_touch_data_tilde_campaign_id': 'Last Attributed Touch Campaign ID',
  'last_attributed_touch_data_tilde_campaign_name': 'Last Attributed Touch Campaign Name',
  'last_attributed_touch_data_tilde_channel': 'Last Attributed Touch Channel',
  'last_attributed_touch_data_tilde_creative_id': 'Last Attributed Touch Creative ID',
  'last_attributed_touch_data_tilde_creative_name': 'Last Attributed Touch Creative Name',
  'last_attributed_touch_data_tilde_customer_ad_name': 'Last Attributed Touch Customer Ad Name',
  'last_attributed_touch_data_tilde_customer_ad_set_name': 'Last Attributed Touch Customer Ad Set Name',
  'last_attributed_touch_data_tilde_customer_campaign': 'Last Attributed Touch Customer Campaign',
  'last_attributed_touch_data_tilde_customer_keyword': 'Last Attributed Touch Customer Keyword',
  'last_attributed_touch_data_tilde_customer_placement': 'Last Attributed Touch Customer Placement',
  'last_attributed_touch_data_tilde_customer_secondary_publisher': 'Last Attributed Touch Customer Secondary Publisher',
  'last_attributed_touch_data_tilde_customer_sub_site_name': 'Last Attributed Touch Customer Sub Site Name',
  'last_attributed_touch_data_tilde_feature': 'Last Attributed Touch Feature',
  'last_attributed_touch_data_tilde_id': 'Last Attributed Touch ID',
  'last_attributed_touch_data_tilde_journey_id': 'Last Attributed Touch Journey ID',
  'last_attributed_touch_data_tilde_journey_name': 'Last Attributed Touch Journey Name',
  'last_attributed_touch_data_tilde_keyword': 'Last Attributed Touch Keyword',
  'last_attributed_touch_data_tilde_keyword_id': 'Last Attributed Touch Keyword ID',
  'last_attributed_touch_data_tilde_placement': 'Last Attributed Touch Placement',
  'last_attributed_touch_data_tilde_secondary_publisher': 'Last Attributed Touch Secondary Publisher',
  'last_attributed_touch_data_tilde_stage': 'Last Attributed Touch Stage',
  'last_attributed_touch_data_tilde_tags': 'Last Attributed Touch Tags',
  'last_attributed_touch_data_tilde_touch_subtype': 'Last Attributed Touch Subtype',
  'last_attributed_touch_data_tilde_view_id': 'Last Attributed Touch View ID',
  'last_attributed_touch_data_tilde_view_name': 'Last Attributed Touch View Name',
  'last_attributed_touch_type': 'Last Attributed Touch Type',
  'last_cta_view_data_dollar_3p': 'Last CTA View 3rd Party',
  'last_cta_view_data_plus_referring_domain': 'Last CTA View Referring Domain',
  'last_cta_view_data_plus_via_features': 'Last CTA View Via Features',
  'last_cta_view_data_plus_web_format': 'Last CTA View Web Format',
  'last_cta_view_data_tilde_ad_id': 'Last CTA View Ad ID',
  'last_cta_view_data_tilde_ad_name': 'Last CTA View Ad Name',
  'last_cta_view_data_tilde_ad_set_id': 'Last CTA View Ad Set ID',
  'last_cta_view_data_tilde_ad_set_name': 'Last CTA View Ad Set Name',
  'last_cta_view_data_tilde_advertising_partner_name': 'Last CTA View Advertising Partner Name',
  'last_cta_view_data_tilde_campaign': 'Last CTA View Campaign',
  'last_cta_view_data_tilde_campaign_id': 'Last CTA View Campaign ID',
  'last_cta_view_data_tilde_channel': 'Last CTA View Channel',
  'last_cta_view_data_tilde_creative_id': 'Last CTA View Creative ID',
  'last_cta_view_data_tilde_creative_name': 'Last CTA View Creative Name',
  'last_cta_view_data_tilde_feature': 'Last CTA View Feature',
  'last_cta_view_data_tilde_journey_id': 'Last CTA View Journey ID',
  'last_cta_view_data_tilde_journey_name': 'Last CTA View Journey Name',
  'last_cta_view_data_tilde_keyword': 'Last CTA View Keyword',
  'last_cta_view_data_tilde_secondary_publisher': 'Last CTA View Secondary Publisher',
  'last_cta_view_data_tilde_stage': 'Last CTA View Stage',
  'last_cta_view_data_tilde_tags': 'Last CTA View Tags',
  'last_cta_view_data_tilde_view_id': 'Last CTA View View ID',
  'last_cta_view_data_tilde_view_name': 'Last CTA View View Name',
  'annotation_campaign_id_mapped_value': 'Annotation Campaign ID Mapped Value',
  'annotation_campaign_id_revision': 'Annotation Campaign ID Revision',
  'annotation_conversion_value_mapped_value': 'Annotation Conversion Value Mapped Value',
  'annotation_conversion_value_revision': 'Annotation Conversion Value Revision',
  'annotation_customer_event_alias': 'Annotation Customer Event Alias',
  'annotation_dollar_3p': 'Annotation 3rd Party',
  'annotation_source_app_id_mapped_value': 'Annotation Source App ID Mapped Value',
  'annotation_source_app_id_revision': 'Annotation Source App ID Revision',
  'user_data_app_store': 'User Data App Store',
  'user_data_app_version': 'User Data App Version',
  'user_data_brand': 'User Data Brand',
  'user_data_country': 'User Data Country',
  'user_data_custom_events_completed': 'User Data Custom Events Completed',
  'user_data_device_type': 'User Data Device Type',
  'user_data_environment': 'User Data Environment',
  'user_data_geo_country_code': 'User Data Geo Country Code',
  'user_data_geo_dma_code': 'User Data Geo DMA Code',
  'user_data_geo_region_en': 'User Data Geo Region',
  'user_data_has_app': 'User Data Has App',
  'user_data_has_clicked_ad': 'User Data Has Clicked Ad',
  'user_data_has_clicked_email': 'User Data Has Clicked Email',
  'user_data_language': 'User Data Language',
  'user_data_model': 'User Data Model',
  'user_data_opted_in': 'User Data Opted In',
  'user_data_opted_in_status': 'User Data Opted In Status',
  'user_data_os': 'User Data OS',
  'user_data_platform': 'User Data Platform',
  'user_data_standard_events_completed': 'User Data Standard Events Completed',
  'event_timezone_adjusted_day': 'Event Timezone Adjusted Day',
  'event_days_from_timestamp': 'Event Days From Timestamp',
  'customer_event_alias': 'Customer Event Alias',
  'days_from_last_attributed_touch_to_event': 'Days From Last Attributed Touch To Event',
  'days_from_last_cta_view_to_event': 'Days From Last CTA View To Event',
  'event_data_custom_param_1': 'Event Data Custom Param 1',
  'event_data_custom_param_2': 'Event Data Custom Param 2',
  'event_data_custom_param_3': 'Event Data Custom Param 3',
  'event_data_product_categories': 'Event Data Product Categories',
  'first_event_for_user': 'First Event For User',
  'fraud_codes': 'Fraud Codes',
  'fraud_names': 'Fraud Names',
  'from_desktop': 'From Desktop'
};

export const crossEventExportDataSources = {
  'eo_install': 'Installs',
  'eo_install_blocked': 'Blocked Installs',
  'eo_impression': 'Impressions',
  'eo_impression_blocked': 'Blocked Impressions',
  'eo_click': 'Clicks',
  'eo_click_blocked': 'Blocked Clicks',
  'eo_reinstall': 'Reinstalls',
  'eo_reinstall_blocked': 'Blocked Reinstalls',
  'eo_open': 'Opens',
  'eo_open_blocked': 'Blocked Opens',
  'eo_web_session_start': 'Web Session Starts',
  'eo_web_session_start_blocked': 'Blocked Web Session Starts',
  'eo_pageview': 'Pageviews',
  'eo_pageview_blocked': 'Blocked Pageviews',
  'eo_dismissal': 'Dismissals',
  'eo_dismissal_blocked': 'Blocked Dismissals',
  'eo_content_event': 'Content Events',
  'eo_content_event_blocked': 'Blocked Content Events',
  'eo_user_lifecycle_event': 'User Lifecycle Events',
  'eo_user_lifecycle_event_blocked': 'Blocked User Lifecycle Events',
  'eo_custom_event': 'Custom Events',
  'eo_custom_event_blocked': 'Blocked Custom Events',
  'eo_branch_cta_view': 'Branch CTA Views',
  'eo_branch_cta_view_blocked': 'Blocked Branch CTA Views',
  'xx_impression': 'Cross-Platform Impressions',
  'xx_click': 'Cross-Platform Clicks',
  'eo_commerce_event': 'Commerce Events',
  'eo_commerce_event_blocked': 'Blocked Commerce Events',
  'link': 'Links',
  'skadnetwork_valid_messages': 'SKAdNetwork Valid Messages',
  'skadnetwork_invalid_messages': 'SKAdNetwork Invalid Messages',
  'cost': 'Cost',
  'cost_actions': 'Cost Actions',
  'cost_clicks': 'Cost Clicks',
  'cost_installs': 'Cost Installs',
  'cost_impressions': 'Cost Impressions',
  'skan_unified_view': 'SKAN Unified View'
};