export const customExportReportTypes = {
  'eo_click_blocked': 'Blocked Clicks',
  'eo_commerce_event_blocked': 'Blocked Commerce Events',
  'eo_content_event_blocked': 'Blocked Content Events',
  'eo_branch_cta_view_blocked': 'Blocked CTA Views',
  'eo_custom_event_blocked': 'Blocked Custom Events',
  'eo_impression_blocked': 'Blocked Impressions',
  'eo_install_blocked': 'Blocked Installs',
  'eo_open_blocked': 'Blocked Opens',
  'eo_pageview_blocked': 'Blocked Pageviews',
  'eo_reinstall_blocked': 'Blocked Reinstalls',
  'eo_sms_sent_blocked': 'Blocked SMS Sent',
  'eo_user_lifecycle_event_blocked': 'Blocked User Lifecycle Events',
  'eo_web_session_start_blocked': 'Blocked Web Session Starts',
  'eo_click': 'Clicks',
  'eo_commerce_event': 'Commerce Events',
  'eo_content_event': 'Content Events',
  'eo_branch_cta_view': 'CTA Views',
  'eo_custom_event': 'Custom Events',
  'eo_impression': 'Impressions',
  'eo_install': 'Installs',
  'eo_open': 'Opens',
  'eo_pageview': 'Pageviews',
  'webhook2': 'Postback Records',
  'eo_reinstall': 'Reinstalls',
  'skadnetwork_invalid_messages': 'SKAdNetwork Invalid Messages',
  'skadnetwork_valid_messages': 'SKAdNetwork Valid Messages',
  'eo_sms_sent': 'SMS Sent',
  'eo_user_lifecycle_event': 'User Lifecycle Events',
  'eo_web_session_start': 'Web Session Starts',
  'eo_san_touch': 'Self-Attributing Network Touch'
};

export const customExportFields = {
  'app_id': 'App ID',
  'app_name': 'App Name',
  'attributed': 'Attributed',
  'content_items': 'Content Items',
  'custom_data': 'Custom Data',
  'customer_event_alias': 'Customer Event Alias',
  'days_from_last_attributed_touch_to_event': 'Days From Last Attributed Touch To Event',
  'deep_linked': 'Deep Linked',
  'di_match_click_token': 'DI Match Click Token',
  'event_data_ad_type': 'Ad Type (BANNER, INTERSTITIAL, REWARDED_VIDEO, NATIVE)',
  'event_data_affiliation': 'Affiliation',
  'event_data_coupon': 'Coupon',
  'event_data_currency': 'Currency',
  'event_data_description': 'Event Description',
  'event_data_exchange_rate': 'Exchange Rate',
  'event_data_revenue': 'Revenue',
  'event_data_revenue_in_usd': 'Revenue In USD',
  'event_data_search_query': 'Search Query',
  'event_data_shipping': 'Shipping',
  'event_data_tax': 'Tax',
  'event_data_transaction_id': 'Transaction ID',
  'event_data_local_currency': 'Local Currency',
  'event_data_local_currency_exchange_rate': 'Local Currency Exchange Rate',
  'event_data_revenue_in_local_currency': 'Revenue in Local Currency',
  'event_data_custom_param_1': 'Custom parameter for event',
  'event_data_custom_param_2': 'Custom parameter for event',
  'event_data_custom_param_3': 'Custom parameter for event',
  'event_timestamp': 'Event Timestamp',
  'existing_user': 'Existing User',
  'external_intent_uri': 'External Intent URI',
  'first_event_for_user': 'First Event For User',
  'hash_version': 'Hash Version',
  'hours_from_last_attributed_touch_to_event': 'Hours From Last Attributed Touch To Event',
  'install_activity_touch_data_tilde_ad_name': 'Install Ad Name',
  'install_activity_touch_data_tilde_ad_set_name': 'Install Ad Set Name',
  'install_activity_touch_data_tilde_advertising_partner_id': 'Install Ad Partner ID',
  'install_activity_touch_data_tilde_advertising_partner_name': 'Install Ad Partner',
  'install_activity_touch_data_tilde_agency': 'Install Agency',
  'install_activity_touch_data_tilde_agency_id': 'Install Agency ID',
  'install_activity_touch_data_tilde_campaign': 'Install Campaign',
  'install_activity_touch_data_tilde_channel': 'Install Channel',
  'install_activity_touch_data_tilde_creative_name': 'Install Creative Name',
  'install_activity_touch_data_tilde_customer_ad_name': 'Install Customer Ad Name',
  'install_activity_touch_data_tilde_customer_ad_set_name': 'Install Customer Ad Set Name',
  'install_activity_touch_data_tilde_customer_campaign': 'Install Customer Campaign',
  'install_activity_touch_data_tilde_customer_keyword': 'Install Customer Keyword',
  'install_activity_touch_data_tilde_customer_placement': 'Install Customer Placement',
  'install_activity_touch_data_tilde_customer_secondary_publisher': 'Install Customer Secondary Publisher',
  'install_activity_touch_data_tilde_customer_sub_site_name': 'Install Customer Sub Site Name',
  'install_activity_touch_data_tilde_feature': 'Install Feature',
  'install_activity_touch_data_tilde_journey_name': 'Install Journey Name',
  'install_activity_touch_data_tilde_keyword': 'Install Keyword',
  'install_activity_touch_data_tilde_placement': 'Install Placement',
  'install_activity_touch_data_tilde_secondary_publisher': 'Install Secondary Publisher',
  'install_activity_touch_data_tilde_stage': 'Install Stage',
  'install_activity_touch_data_tilde_tags': 'Install Tags',
  'install_activity_touch_data_tilde_view_name': 'Install View Name',
  'install_activity_touch_type': 'Install Touch Type',
  'last_attributed_touch_data_custom_fields': 'Last Attributed Touch Custom Fields',
  'last_attributed_touch_data_dollar_3p': 'Ad Partner (3p)',
  'last_attributed_touch_data_dollar_marketing_title': 'Marketing Title',
  'last_attributed_touch_data_plus_current_feature': 'Current Feature',
  'last_attributed_touch_data_tilde_id': 'Last Attributed Touch ID',
  'last_attributed_touch_data_plus_touch_id': 'Last Attributed Touch Touch ID',
  'last_attributed_touch_data_plus_url': 'URL',
  'last_cta_view_data_plus_touch_id': 'Last CTA View Touch ID',
  'last_attributed_touch_data_plus_via_features': 'Via Features',
  'last_attributed_touch_data_plus_web_format': 'Web Format',
  'last_attributed_touch_data_tilde_ad_id': 'Ad ID',
  'last_attributed_touch_data_tilde_ad_name': 'Ad Name',
  'last_attributed_touch_data_tilde_ad_set_id': 'Ad Set ID',
  'last_attributed_touch_data_tilde_ad_set_name': 'Ad Set Name',
  'last_attributed_touch_data_tilde_advertising_account_name': 'Advertising Account Name',
  'last_attributed_touch_data_tilde_advertising_account_id': 'Advertising Account ID',
  'last_attributed_touch_data_tilde_advertising_partner_id': 'Ad Partner ID',
  'last_attributed_touch_data_tilde_advertising_partner_name': 'Ad Partner',
  'last_attributed_touch_data_tilde_agency': 'Agency',
  'last_attributed_touch_data_tilde_agency_id': 'Agency ID',
  'last_attributed_touch_data_tilde_banner_dimensions': 'Banner Dimensions',
  'last_attributed_touch_data_tilde_branch_ad_format': 'Branch Ad Format',
  'last_attributed_touch_data_tilde_campaign': 'Campaign',
  'last_attributed_touch_data_tilde_campaign_id': 'Campaign ID',
  'last_attributed_touch_data_tilde_campaign_type': 'Campaign Type',
  'last_attributed_touch_data_tilde_channel': 'Channel',
  'last_attributed_touch_data_tilde_creative_id': 'Creative ID',
  'last_attributed_touch_data_tilde_creative_name': 'Creative Name',
  'last_attributed_touch_data_tilde_journey_id': 'Journey ID',
  'last_attributed_touch_data_tilde_journey_name': 'Journey Name',
  'last_attributed_touch_data_tilde_keyword': 'Keyword',
  'last_attributed_touch_data_tilde_keyword_id': 'Keyword ID',
  'last_attributed_touch_data_tilde_optimization_model': 'Optimization Model',
  'last_attributed_touch_data_tilde_placement': 'Placement',
  'last_attributed_touch_data_tilde_placement_id': 'Placement ID',
  'last_attributed_touch_data_tilde_secondary_ad_format': 'Secondary Ad Format',
  'last_attributed_touch_data_tilde_secondary_publisher': 'Secondary Publisher',
  'last_attributed_touch_data_tilde_secondary_publisher_id': 'Secondary Publisher ID',
  'last_attributed_touch_data_tilde_stage': 'Stage',
  'last_attributed_touch_data_tilde_sub_site_name': 'Sub Site Name',
  'last_attributed_touch_data_tilde_tags': 'Tags',
  'last_attributed_touch_data_tilde_technology_partner': 'Technology Partner',
  'last_attributed_touch_data_tilde_touch_subtype': 'Google Video Ads "Engaged View"',
  'last_attributed_touch_data_tilde_view_id': 'View ID',
  'last_attributed_touch_data_tilde_view_name': 'View Name',
  'last_attributed_touch_timestamp': 'Last Attributed Touch Timestamp',
  'last_attributed_touch_timestamp_iso': 'Last Attributed Touch Timestamp (ISO)',
  'last_attributed_touch_type': 'Last Attributed Touch Type',
  'last_cta_view_data_custom_fields': 'Last CTA View Custom Fields',
  'last_cta_view_data_dollar_3p': 'Last CTA View Ad Partner (3p)',
  'last_attributed_touch_data_plus_referring_domain': 'Referring Domain',
  'last_cta_view_data_plus_via_features': 'Last CTA View Via Features',
  'last_cta_view_data_plus_web_format': 'Last CTA View Web Format',
  'last_cta_view_data_tilde_ad_id': 'Last CTA View Ad ID',
  'last_cta_view_data_tilde_ad_name': 'Last CTA View Ad Name',
  'last_cta_view_data_tilde_ad_set_id': 'Last CTA View Ad Set ID',
  'last_cta_view_data_tilde_ad_set_name': 'Last CTA View Ad Set Name',
  'last_cta_view_data_tilde_advertising_partner_name': 'Last CTA View Ad Partner',
  'last_cta_view_data_tilde_agency': 'Last CTA View Agency',
  'last_cta_view_data_tilde_banner_dimensions': 'Last CTA View Banner Dimensions',
  'last_cta_view_data_tilde_branch_ad_format': 'Last CTA View Branch Ad Format',
  'last_cta_view_data_tilde_campaign': 'Last CTA View Campaign',
  'last_cta_view_data_tilde_campaign_id': 'Last CTA View Campaign ID',
  'last_cta_view_data_tilde_campaign_type': 'Last CTA View Campaign Type',
  'last_cta_view_data_tilde_channel': 'Last CTA View Channel',
  'last_cta_view_data_tilde_creative_id': 'Last CTA View Creative ID',
  'last_cta_view_data_tilde_creative_name': 'Last CTA View Creative Name',
  'last_cta_view_data_tilde_external_touch_id': 'Last CTA View External Touch ID',
  'last_cta_view_data_tilde_feature': 'Last CTA View Feature',
  'last_cta_view_data_tilde_id': 'Last CTA View ID',
  'last_cta_view_data_tilde_keyword_id': 'Last CTA View Keyword ID',
  'last_cta_view_data_tilde_optimization_model': 'Last CTA View Optimization Model',
  'last_cta_view_data_tilde_placement': 'Last CTA View Placement',
  'last_cta_view_data_tilde_secondary_ad_format': 'Last CTA View Secondary Ad Format',
  'last_cta_view_data_tilde_secondary_publisher': 'Last CTA View Secondary Publisher',
  'last_cta_view_data_tilde_stage': 'Last CTA View Stage',
  'last_cta_view_data_tilde_tags': 'Last CTA View Tags',
  'last_cta_view_data_tilde_technology_partner': 'Last CTA View Technology Partner',
  'reengagement_activity_touch_data_additional_data_tilde_ad_set_id': 'Reengagement Ad Set ID',
  'reengagement_activity_touch_data_additional_data_tilde_campaign_id': 'Reengagement Campaign ID',
  'reengagement_activity_touch_data_additional_data_tilde_creative_id': 'Reengagement Creative ID',
  'reengagement_activity_touch_data_dollar_3p': 'Reengagement Partner 3p Value',
  'reengagement_activity_touch_data_plus_via_features': 'Reengagement Features',
  'reengagement_activity_touch_data_plus_web_format': 'Reengagement Web Format',
  'reengagement_activity_touch_data_tilde_ad_name': 'Reengagement Ad Name',
  'reengagement_activity_touch_data_tilde_ad_set_name': 'Reengagement Ad Set Name',
  'reengagement_activity_touch_data_tilde_advertising_partner_id': 'Reengagement Advertising Partner ID',
  'reengagement_activity_touch_data_tilde_advertising_partner_name': 'Reengagement Advertising Partner Name',
  'reengagement_activity_touch_data_tilde_agency': 'Reengagement Agency',
  'reengagement_activity_touch_data_tilde_agency_id': 'Reengagement Agency ID',
  'reengagement_activity_touch_data_tilde_campaign': 'Reengagement Campaign',
  'reengagement_activity_touch_data_tilde_channel': 'Reengagement Channel',
  'reengagement_activity_touch_data_tilde_creative_name': 'Reengagement Creative Name',
  'reengagement_activity_touch_data_tilde_customer_ad_name': 'Reengagement Customer Ad Name',
  'reengagement_activity_touch_data_tilde_customer_ad_set_name': 'Reengagement Customer Ad Set Name',
  'reengagement_activity_touch_data_tilde_customer_campaign': 'Reengagement Customer Campaign',
  'reengagement_activity_touch_data_tilde_customer_keyword': 'Reengagement Customer Keyword',
  'reengagement_activity_touch_data_tilde_customer_placement': 'Reengagement Customer Placement',
  'reengagement_activity_touch_data_tilde_customer_secondary_publisher': 'Reengagement Customer Secondary Publisher',
  'reengagement_activity_touch_data_tilde_customer_sub_site_name': 'Reengagement Customer Sub Site',
  'reengagement_activity_touch_data_tilde_feature': 'Reengagement Feature',
  'reengagement_activity_touch_data_tilde_journey_name': 'Reengagement Journey Name',
  'reengagement_activity_touch_data_tilde_keyword': 'Reengagement Keyword',
  'reengagement_activity_touch_data_tilde_placement': 'Reengagement Placement',
  'reengagement_activity_touch_data_tilde_secondary_publisher': 'Reengagement Secondary Publisher',
  'reengagement_activity_touch_data_tilde_stage': 'Reengagement Stage',
  'reengagement_activity_touch_data_tilde_tags': 'Reengagement Tags',
  'reengagement_activity_touch_data_tilde_view_name': 'Reengagement View Name',
  'reengagement_activity_touch_type': 'Reengagement Touch Type',
  'referrer_click_timestamp': 'Referrer Click Timestamp',
  'seconds_from_install_to_event': 'Seconds From Install To Event',
  'seconds_from_last_attributed_touch_to_event': 'Seconds From Last Attributed Touch To Event',
  'seconds_from_last_attributed_touch_to_store_install_begin': 'Seconds From Touch To Store Install Begin',
  'site_event_items_count': 'Content Items Count',
  'store_install_begin_timestamp': 'Store Install Begin Timestamp',
  'timestamp': 'Timestamp',
  'timestamp_iso': 'Timestamp (ISO)',
  'user_data_aaid': 'AAID',
  'user_data_android_id': 'Android ID',
  'user_data_app_version': 'App Version',
  'user_data_brand': 'Brand',
  'user_data_browser': 'Browser',
  'user_data_build': 'Build',
  'user_data_cpp_level': 'The Consumer Protection Preference level',
  'user_data_device_type': 'Device Type',
  'user_data_environment': 'Environment',
  'user_data_geo_city_code': 'City Code',
  'user_data_geo_city_en': 'City',
  'user_data_geo_country_code': 'Country Code',
  'user_data_geo_country_en': 'Country',
  'user_data_geo_dma_code': 'DMA Code',
  'user_data_geo_lat': 'Latitude',
  'user_data_geo_lon': 'Longitude',
  'user_data_geo_postal_code': 'Postal Code',
  'user_data_geo_region_en': 'Region',
  'user_data_geo_region_code': 'Region Code',
  'user_data_http_referrer': 'HTTP Referrer',
  'user_data_idfa': 'IDFA',
  'user_data_idfv': 'IDFV',
  'user_data_internet_connection_type': 'Internet Connection Type',
  'user_data_ip': 'IP Address',
  'user_data_is_jailbroken': 'Is Jailbroken',
  'user_data_kindle_id': 'Kindle ID',
  'user_data_language': 'Language',
  'user_data_limit_ad_tracking': 'Limit Ad Tracking',
  'user_data_model': 'Model',
  'user_data_oaid': 'Huawei OAID',
  'user_data_os': 'OS',
  'user_data_os_version': 'OS Version',
  'user_data_os_version_android': 'OS Version (Android)',
  'user_data_past_cross_platform_ids': 'Past Cross Platforms IDs',
  'user_data_platform': 'Platform',
  'user_data_prob_cross_platform_ids': 'Probabilistic Cross Platform IDs',
  'user_data_roku_rida': 'Roku Device ID',
  'user_data_screen_height': 'Screen Height',
  'user_data_screen_width': 'Screen Width',
  'user_data_sdk_version': 'SDK Version',
  'user_data_user_agent': 'User Agent',
  'user_data_windows_aid': 'Windows AID',
  'user_data_device_locale': 'Device Locale',
  'user_data_carrier_name': 'Carrier Name',
  'user_data_opted_in_status': 'Whether user opted in to ATT or not',
  'user_data_app_store': 'The app store the user downloaded from'
};